#配置文件名
clarkConfigName: clark-supplier-dev.yml

#feign中的ribbon超时配置
ribbon:
  # 连接超时
  ConnectTimeout: 5000
  # 响应超时
  ReadTimeout: 5000
  
spring:
  cloud:
    #消息总线配置
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        #开启总线消息更新功能
        enabled: true
  #配置rabbitMQ
  rabbitmq:
    host: 192.168.224.134
    port: 5672
    username: guest
    password: guest
