#配置文件名
clarkConfigName: clark-supplier-dev.yml

#feign超时配置
ribbon:
  # 连接超时
  ConnectTimeout: 5000
  # 响应超时
  ReadTimeout: 5000

#配置hystrix超时
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
