
###服务启动端口号
server:
  port: 9001
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: clark-supplier
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka
    register-with-eureka: true
    fetch-registry: true

#feign超时配置
ribbon:
  # 连接超时
  ConnectTimeout: 5000
  # 响应超时
  ReadTimeout: 5000

#配置hystrix超时
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
