#配置rabbitMQ 
  rabbitmq:
    host: 192.168.224.134
    port: 5672
    username: guest
    password: guest
#网关配置
zuul:
  ignored-services: "*"
  #请求转发时去掉转发路径（path中的值）
  strip-prefix: true
  routes:
    #所有以/consumer开头的请求都转发到clark-consumer应用
    api-clark-consumer:
      path: /consumer/**
      serviceId: clark-consumer
    #所有以/consumer开头的请求都转发到clark-consumer应用
    api-clark-supplier:
      path: /supplier/**
      serviceId: clark-supplier
